// Variable a utiliser pour tester

export const Employe =[
    {      
        "nom": "Alice Dupont",
        "email": "alice.dupont@example.com",
        "telephone": "555-1234",
        "adresse": "123 Rue de Paris",
        "mot_de_passe": "password1",
        "photo": " ",
        "date_d_embauche": "2023-01-15",
       
    },
    {  
        "nom": "Bob Martin",
        "email": "bob.martin@example.com",
        "telephone": "555-5678",
        "adresse": "456 Avenue de Lyon",
        "mot_de_passe": "password2",
        "photo": "https://example.com/photos/bob.jpg",
        "date_d_embauche": "2022-11-10", 
    },
    { 
        "nom": "Clara Lemoine",
        "email": "clara.lemoine@example.com",
        "telephone": "555-9876",
        "adresse": "789 Boulevard de Marseille",
        "mot_de_passe": "password3",
        "photo": "https://example.com/photos/clara.jpg",
        "date_d_embauche": "2023-05-20",
    },
    {
        "nom": "David Lopez",
        "email": "david.lopez@example.com",
        "telephone": "555-6543",
        "adresse": "321 Rue de Nice",
        "mot_de_passe": "password4",
        "photo": "https://example.com/photos/david.jpg",
        "date_d_embauche": "2021-09-12",  
    },
    {
        "nom": "Emma Fournier",
        "email": "emma.fournier@example.com",
        "telephone": "555-4321",
        "adresse": "654 Avenue de Bordeaux",
        "mot_de_passe": "password5",
        "photo": "https://example.com/photos/emma.jpg",
        "date_d_embauche": "2022-04-28",   
    },
    {  
        "nom": "François Dubois",
        "email": "francois.dubois@example.com",
        "telephone": "555-7890",
        "adresse": "789 Rue de Lille",
        "mot_de_passe": "password6",
        "photo": "https://example.com/photos/francois.jpg",
        "date_d_embauche": "2023-07-01",
    },
    { 
        "nom": "Gabrielle Morin",
        "email": "gabrielle.morin@example.com",
        "telephone": "555-8765",
        "adresse": "123 Boulevard de Nantes",
        "mot_de_passe": "password7",
        "photo": "https://example.com/photos/gabrielle.jpg",
        "date_d_embauche": "2022-12-05",
    },
    { 
        "nom": "Henri Lefevre",
        "email": "henri.lefevre@example.com",
        "telephone": "555-3456",
        "adresse": "456 Rue de Brest",
        "mot_de_passe": "password8",
        "photo": "https://example.com/photos/henri.jpg",
        "date_d_embauche": "2023-03-11",
    },
    { 
        "nom": "Isabelle Laurent",
        "email": "isabelle.laurent@example.com",
        "telephone": "555-2109",
        "adresse": "321 Avenue de Toulouse",
        "mot_de_passe": "password9",
        "photo": "https://example.com/photos/isabelle.jpg",
        "date_d_embauche": "2021-06-14",
    },
    {  
        "nom": "Jacques Bernard",
        "email": "jacques.bernard@example.com",
        "telephone": "555-1098",
        "adresse": "789 Rue de Montpellier",
        "mot_de_passe": "password10",
        "photo": "https://example.com/photos/jacques.jpg",
        "date_d_embauche": "2020-08-23", 
    }
]
